### ISSUE TITLE
[NBS] Document error codes

### ISSUE THREAD

**Issue by drbasic** [ydb-platform/nbs#2282]
Нужно документировать коды ошибок из https://github.com/ydb-platform/nbs/blob/main/cloud/storage/core/libs/common/error.h#L100
Описать что означает код и тонкости его применения.

**Comment by drbasic** [comment]
Для начала предлагаю согласовать текст, а потом я перенесу его в репозиторий.

// Успешные коды
S_OK   // Операция выполнена успешно
S_FALSE  // Запрошенная операция не была выполнена, потому что объект не существует, операцию не к чему применить. 
S_ALREADY // Запрошенная операция не была выполнена, потому что объект уже находится в нужном состоянии. 

// Ошибки
E_FAIL  // 
E_ARGUMENT 
E_REJECTED

**Comment by drbasic** [comment]
// Коды успеха
S_OK  // Запрос выполнен успешно
S_FALSE  // Запрос не выполнен потому что объекта не существует
S_ALREADY // Запрос не выполнен, так как объект уже находится в необходимом состоянии

// Коды ошибок
E_FAIL  // 
    E_ARGUMENT         
    E_REJECTED          

    E_INVALID_STATE          
    E_TIMEOUT                 
    E_NOT_FOUND           
    E_UNAUTHORIZED     
    E_NOT_IMPLEMENTED
    E_ABORTED                  
    E_TRY_AGAIN               
    E_IO                       
    E_CANCELLED     
    E_IO_SILENT        
    E_RETRY_TIMEOUT 
    E_PRECONDITION_FAILED

**Comment by ya-ksgamora** [comment]
Below is an English translation of the Russian text:

// Success codes

S_OK  // The request was executed successfully
S_FALSE  // The request was not executed because the object does not exist; there is nothing to operate on
S_ALREADY // The request was not executed because the object is already in the required state

// Error codes

E_INVALID_STATE // The object is in an inappropriate state to perform the request
E_TIMEOUT  // The underlying layer did not complete within the time limit
E_NOT_FOUND  // The object was not found
E_UNAUTHORIZED  // Authorization error
E_NOT_IMPLEMENTED // The request is not implemented or should not be implemented
E_ABORTED  // This request must not be retried; you should retry the higher-level request instead
E_TRY_AGAIN // The control-plane request cannot be executed at this time; please try again later. Unlike E_REJECTED, which can be retried immediately
E_IO  // Input/output error. This is fatal, indicating it is impossible to read or write a block due to hardware failure
E_IO_SILENT // A legacy code for input/output errors. Unlike E_IO, it does not increment the fatal error counter in monitoring
E_CANCELLED  // The request execution was stopped at the initiative of the client (e.g., client disconnected)
E_RETRY_TIMEOUT // The total time limit (24 hours) for executing the request has expired
E_PRECONDITION_FAILED  // Preconditions within the object have been violated. This error is not retryable

// Flags

EF_SILENT  // A flag that makes the error EErrorKind::ErrorSilent. Such an error does not increment the fatal error counter. Caution: using this flag with a retryable error makes it non-retryable
EF_HW_PROBLEMS_DETECTED // A flag indicating a problem with the NRD or the disk agent
